repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
    types: [python, yaml, markdown, toml]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.16.7
    hooks:
      # Ruff's settings are configured in the pyproject.toml file
      - id: ruff
        args: ["--fix", "--show-fixes"]
        files: ^fastfem/
      - id: ruff-format
        args: ["fastfem"]
    types: [python, yaml, markdown, toml]
